[MeterContainerVisible]
Meter = Shape
Shape = Rectangle #Spacing.margin.horizontal#, #Spacing.margin.vertical#, (#Spacing.padding.horizontal# + #Spacing.content.width# + #Spacing.padding.horizontal#), #Spacing.window.height# | Fill Color #Color.background# | StrokeWidth 0

[MeterContainer]
Meter = Shape
Shape = Rectangle #Spacing.margin.horizontal#, #Spacing.margin.vertical#, (#Spacing.padding.horizontal# + #Spacing.content.width# + #Spacing.padding.horizontal#), #Spacing.window.height# | StrokeWidth 0
