[styleLeftText]
StringAlign = LEFT
FontColor = #colorText#
FontFace = #fontName#
FontSize = #textSize#
AntiAlias = 1
Container = MeterContainer

[styleBar]
BarOrientation = HORIZONTAL
BarColor = #colorBar#
SolidColor = #colorGraphBackground#
X = r
Y = r
W = #contentWidth#
H = 3
Container = MeterContainer

[styleBarVertical]
BarOrientation = VERTICAL
BarColor = #colorCPU#
SolidColor = #colorGraphBackground#
X = r
Y = r
W = #barWidth#
H = 20
Container = MeterContainer

[styleGraph]
BarOrientation = HORIZONTAL
GraphStart = Right
SolidColor = #colorGraphBackground#
Antialias = 1
X = r
Y = 20r
W = #contentWidth#
H = 30
Container = MeterContainer

[styleGraphSmall]
BarOrientation = HORIZONTAL
GraphStart = Right
SolidColor = #colorGraphBackground#
Antialias = 1
X = r
Y = 20r
W = #contentWidth#
H = 20
Container = MeterContainer
