[styleLeftText]
StringAlign = LEFT
FontColor = #colorText#
FontFace = #fontName#
FontSize = #textSize#
AntiAlias = 1
Container = MeterContainer

[styleBar]
BarColor = #colorBar#
BarColor = #colorBar#
SolidColor = #colorGraphBackground#
X = r
Y = 36r
W = #contentWidth#
H = 3
Container = MeterContainer

[styleGraph]
BarOrientation = HORIZONTAL
GraphStart = Right
SolidColor = #colorGraphBackground#
Antialias = 1
X = r
Y = 20r
W = #contentWidth#
H = 30
Container = MeterContainer
