[Variables]
; ==================
; UI style variables
; ==================

fontName = Segoe UI
textSize = 9
colorBackground = 0, 0, 0, 175
colorBar = 255, 140, 0, 200
colorText = 255, 255, 255, 200
colorGraphBackground = 255, 255, 255, 15

colorNeutral = 200, 200, 200, 150
colorIntel = 0, 113, 197, 150  ; #0071C5
colorNvidia = 118, 185, 0, 150 ; #76B900
colorAmd = 221, 0, 49, 150     ; #DD0031

; To use Intel/AMD/NVIDIA colors, set these to the appropriate variable names (listed above)
colorCPU = #colorNeutral#
colorGPU = #colorNeutral#

; default container height, override in specific skins
containerHeight = 70

; this controls the overall width of the skin
contentWidth = 112

marginX = 7
marginY = 6
paddingX = 14
paddingY = 11

barWidth = 7

; ============
; CPU/RAM info
; ============

CPUName = Intel Core i9-9900K

; ============
; Network info
; ============
networkName = Ethernet

; ========
; GPU info
; ========

gpuName = NVIDIA RTX 2080 Ti
vramInBytes = 12188647424‬ ; 11GB
